import { Client } from '@/types';

export const clients: Client[] = [
  {
    id: '0',
    Fullname: 'John Travolta',
    ClientType: 'Private',
    Address: '2464 Royal Ln. Mesa, New Jersey 45463',
    Housenumber: 'Lorem ipsum dolor sit amet consectetur.',
    City: 'Amsterdam',
    Country: 'Netherlands',
    Email: 'name@email.com',
    Telephone: '(209) 555-0104',
  },
  {
    id: '1',
    Fullname: 'John Travolta',
    ClientType: 'Private',
    Address: '2464 Royal Ln. Mesa, New Jersey 45463',
    Housenumber: 'Lorem ipsum dolor sit amet consectetur.',
    City: 'Amsterdam',
    Country: 'Netherlands',
    Email: 'name@email.com',
    Telephone: '(209) 555-0104',
  },
  {
    id: '2',
    Fullname: 'John Travolta',
    ClientType: 'Private',
    Address: '2464 Royal Ln. Mesa, New Jersey 45463',
    Housenumber: 'Lorem ipsum dolor sit amet consectetur.',
    City: 'Amsterdam',
    Country: 'Netherlands',
    Email: 'name@email.com',
    Telephone: '(209) 555-0104',
  },
  {
    id: '3',
    Fullname: 'John Travolta',
    ClientType: 'Private',
    Address: '2464 Royal Ln. Mesa, New Jersey 45463',
    Housenumber: 'Lorem ipsum dolor sit amet consectetur.',
    City: 'Amsterdam',
    Country: 'Netherlands',
    Email: 'name@email.com',
    Telephone: '(209) 555-0104',
  },
  {
    id: '4',
    Fullname: 'John Travolta',
    ClientType: 'Private',
    Address: '2464 Royal Ln. Mesa, New Jersey 45463',
    Housenumber: 'Lorem ipsum dolor sit amet consectetur.',
    City: 'Amsterdam',
    Country: 'Netherlands',
    Email: 'name@email.com',
    Telephone: '(209) 555-0104',
  },
  {
    id: '5',
    Fullname: 'John Travolta',
    ClientType: 'Private',
    Address: '2464 Royal Ln. Mesa, New Jersey 45463',
    Housenumber: 'Lorem ipsum dolor sit amet consectetur.',
    City: 'Amsterdam',
    Country: 'Netherlands',
    Email: 'name@email.com',
    Telephone: '(209) 555-0104',
  },
];
