import { Client } from '@/types';

export const clients: Client[] = [
  {
    id: '0',
    'Full name': 'John Travolta',
    'Client Type': 'Private',
    Address: '2464 Royal Ln. Mesa, New Jersey 45463',
    'House number': 'Lorem ipsum dolor sit amet consectetur.',
    City: 'Amsterdam',
    Country: 'Netherlands',
    Email: 'name@email.com',
    Telephone: '(209) 555-0104',
  },
  {
    id: '1',
    'Full name': 'John Travolta',
    'Client Type': 'Private',
    Address: '2464 Royal Ln. Mesa, New Jersey 45463',
    'House number': 'Lorem ipsum dolor sit amet consectetur.',
    City: 'Amsterdam',
    Country: 'Netherlands',
    Email: 'name@email.com',
    Telephone: '(209) 555-0104',
  },
  {
    id: '2',
    'Full name': 'John Travolta',
    'Client Type': 'Private',
    Address: '2464 Royal Ln. Mesa, New Jersey 45463',
    'House number': 'Lorem ipsum dolor sit amet consectetur.',
    City: 'Amsterdam',
    Country: 'Netherlands',
    Email: 'name@email.com',
    Telephone: '(209) 555-0104',
  },
  {
    id: '3',
    'Full name': 'John Travolta',
    'Client Type': 'Private',
    Address: '2464 Royal Ln. Mesa, New Jersey 45463',
    'House number': 'Lorem ipsum dolor sit amet consectetur.',
    City: 'Amsterdam',
    Country: 'Netherlands',
    Email: 'name@email.com',
    Telephone: '(209) 555-0104',
  },
  {
    id: '4',
    'Full name': 'John Travolta',
    'Client Type': 'Private',
    Address: '2464 Royal Ln. Mesa, New Jersey 45463',
    'House number': 'Lorem ipsum dolor sit amet consectetur.',
    City: 'Amsterdam',
    Country: 'Netherlands',
    Email: 'name@email.com',
    Telephone: '(209) 555-0104',
  },
  {
    id: '5',
    'Full name': 'John Travolta',
    'Client Type': 'Private',
    Address: '2464 Royal Ln. Mesa, New Jersey 45463',
    'House number': 'Lorem ipsum dolor sit amet consectetur.',
    City: 'Amsterdam',
    Country: 'Netherlands',
    Email: 'name@email.com',
    Telephone: '(209) 555-0104',
  },
];
