import { Project } from '@/components/custom/DataTable';

export const projects: Project[] = [
  {
    id: '0',
    'Project number': 'PR001A',
    Date: 'February 29, 2012',
    Category: 'Tile Work',
    Details: 'Lorem ipsum dolor sit amet consectetur.',
    Name: 'Eleanor Pena',
    Address: '2464 Royal Ln. Mesa, New Jersey 45463',
    City: 'Naperville',
    Telephone: '(209) 555-0104',
    Status: 'FINISHED',
  },
  {
    id: '1',
    'Project number': 'PR001A',
    Date: 'February 29, 2012',
    Category: 'Tile Work',
    Details: 'Lorem ipsum dolor sit amet consectetur.',
    Name: 'Eleanor Pena',
    Address: '2464 Royal Ln. Mesa, New Jersey 45463',
    City: 'Naperville',
    Telephone: '(209) 555-0104',
    Status: 'APPROVED',
  },
  {
    id: '2',
    'Project number': 'PR001A',
    Date: 'February 29, 2012',
    Category: 'Tile Work',
    Details: 'Lorem ipsum dolor sit amet consectetur.',
    Name: 'Eleanor Pena',
    Address: '2464 Royal Ln. Mesa, New Jersey 45463',
    City: 'Naperville',
    Telephone: '(209) 555-0104',
    Status: 'PENDING',
  },
  {
    id: '3',
    'Project number': 'PR001A',
    Date: 'February 29, 2012',
    Category: 'Tile Work',
    Details: 'Lorem ipsum dolor sit amet consectetur.',
    Name: 'Eleanor Pena',
    Address: '2464 Royal Ln. Mesa, New Jersey 45463',
    City: 'Naperville',
    Telephone: '(209) 555-0104',
    Status: 'ON HOLD',
  },
  {
    id: '4',
    'Project number': 'PR001A',
    Date: 'February 29, 2012',
    Category: 'Tile Work',
    Details: 'Lorem ipsum dolor sit amet consectetur.',
    Name: 'Eleanor Pena',
    Address: '2464 Royal Ln. Mesa, New Jersey 45463',
    City: 'Naperville',
    Telephone: '(209) 555-0104',
    Status: 'DECLINED',
  },
];
