import { Project } from '@/types';

export const projects: Project[] = [
  {
    id: '0',
    ProjectNumber: 'PR001A',
    Date: 'February 29, 2012',
    Category: 'Tile Work',
    Details: 'Completed tile installation in residential kitchen.',
    Name: 'Eleanor Pena',
    Address: '2464 Royal Ln. Mesa, New Jersey 45463',
    City: 'Naperville',
    Telephone: '(209) 555-0104',
    Status: 'Finished',
  },
  {
    id: '1',
    ProjectNumber: 'PR002B',
    Date: 'March 15, 2013',
    Category: 'Electrical',
    Details: 'Upgraded electrical panels and wiring to meet code in an office building.',
    Name: 'Oliver Hansen',
    Address: '105 N. Bishop Ave. Dallas, Texas 75208',
    City: 'Dallas',
    Telephone: '(214) 555-0187',
    Status: 'Approved',
  },
  {
    id: '2',
    ProjectNumber: 'PR003C',
    Date: 'April 22, 2014',
    Category: 'Plumbing',
    Details: 'Replaced old plumbing lines in commercial complex.',
    Name: 'Theo Sosa',
    Address: '9938 E. Maple St. Denver, Colorado 80230',
    City: 'Denver',
    Telephone: '(303) 555-0119',
    Status: 'Pending',
  },
  {
    id: '3',
    ProjectNumber: 'PR004D',
    Date: 'May 28, 2015',
    Category: 'Renovation',
    Details: 'Full renovation of historical landmark.',
    Name: 'Ivy Mckinney',
    Address: '500 S. Lake Park Ave. Hobart, Indiana 46342',
    City: 'Hobart',
    Telephone: '(219) 555-0131',
    Status: 'On Hold',
  },
  {
    id: '4',
    ProjectNumber: 'PR005E',
    Date: 'June 30, 2016',
    Category: 'Landscaping',
    Details: 'Landscaping services for newly developed parks.',
    Name: 'Luna Love',
    Address: '2233 W. Belmont Ave. Fresno, California 93728',
    City: 'Fresno',
    Telephone: '(559) 555-0142',
    Status: 'Declined',
  },
];
