import { Quotation } from '@/types';

export const quotations: Quotation[] = [
  {
    id: 0,
    quotationNumber: 'PR001A',
    category: 'Tile work',
    details: 'Lorem ipsum dolor sit amet consectetur.',
    date: 'March 23, 2013',
    name: 'Robert Fox',
    address: '1901 Thornridge Cir. Shiloh, Hawaii 81063',
    city: 'Naperville',
    amount: 234.0,
    telephone: '(205) 555-0100',
    status: 'SEND',
  },
  {
    id: 1,
    quotationNumber: 'PR001A',
    category: 'Tile work',
    details: 'Lorem ipsum dolor sit amet consectetur.',
    date: 'March 23, 2013',
    name: 'Robert Fox',
    address: '1901 Thornridge Cir. Shiloh, Hawaii 81063',
    city: 'Naperville',
    amount: 234.0,
    telephone: '(205) 555-0100',
    status: 'SEND',
  },
  {
    id: 2,
    quotationNumber: 'PR001A',
    category: 'Tile work',
    details: 'Lorem ipsum dolor sit amet consectetur.',
    date: 'March 23, 2013',
    name: 'Robert Fox',
    address: '1901 Thornridge Cir. Shiloh, Hawaii 81063',
    city: 'Naperville',
    amount: 234.0,
    telephone: '(205) 555-0100',
    status: 'SEND',
  },
  {
    id: 3,
    quotationNumber: 'PR001A',
    category: 'Tile work',
    details: 'Lorem ipsum dolor sit amet consectetur.',
    date: 'March 23, 2013',
    name: 'Robert Fox',
    address: '1901 Thornridge Cir. Shiloh, Hawaii 81063',
    city: 'Naperville',
    amount: 234.0,
    telephone: '(205) 555-0100',
    status: 'DRAFT',
  },
];
